FROM mysql:8.0

RUN apt-get update && apt-get install -y tzdata

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

COPY ./init.sql /docker-entrypoint-initdb.d/
COPY ./schema.sql /docker-entrypoint-initdb.d/