version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: